lang:         en
title:        Justin Corbett
description:  >
  The personal website of Justin Corbett. Projects, writing, and things worth sharing.

logo:         /assets/img/logo.png

author:
  name:       Justin Corbett
  email:      justin@corbett.ai
  twitter:    _ustin
  github:     jcorbett

copyright:    "© 2026 Justin Corbett"

permalink:    /:categories/:year-:month-:day-:title/
paginate:     10
paginate_path: /:num/

twitter:
  username:   _ustin

social:
  name:       Justin Corbett
  links:
    - https://twitter.com/_ustin

collections:
  projects:
    permalink: /projects/:path/
    output:    true

defaults:
  - scope:
      path: assets/
    values:
      sitemap: false
  - scope:
      path: licenses/
    values:
      layout:  page
      sitemap: false
  - scope:
      type: projects
    values:
      layout: project
      seo:
        type: WebPage
  - scope:
      type: posts
    values:
      layout: post

exclude:
  - .jekyll-cache
  - .sass-cache
  - .ruby-lsp
  - vendor
  - Gemfile
  - Gemfile.lock

include:
  - .well-known
  - LICENSE.md

plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true

relative_links:
  collections: true

titles_from_headings:
  strip_title:  true
  collections:  true

compress_html:
  comments:  ["<!--", "-->"]
  clippings: all
  endings:   all
  ignore:
    envs: [development]

sass:
  style: compressed

kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
